lsst/ap_pipe

- .gitignore
- hits_ingest.py
Note: some of these commits have different usernames because git knew me as "mrawls" on lsst-dev and "Meredith Rawls" on my laptop. I have fixed it so both places use my full name.
> DM-8798: Ingest HiTS calibration products and test on raw images

- .gitignore
- python/lsst/ap/pipe/ap_pipe.py
- tests/test_appipe.py
- ups/ap_pipe.table
This PR adds a wrapper for `AssociationTask` and calls it from `runPipelineAlone()`. The wrapper is treated as analogously as possible to the other pipeline steps.
> DM-12256: Incorporate AssociationTask into ap_pipe

- python/lsst/ap/pipe/ap_pipe.py
This PR does some refactoring of the interface between `ap_pipe` and `ap_verify` prior to the latter calling `doAssociation`.
The new API avoids exposing the file selector and repository structure to outside clients. The internal structure of the code had been left unchanged, so that the ability to potentially customize these aspects when running `ap_pipe` from the command line is still present.
> DM-12257: Implement association step in ap_verify

- python/lsst/ap/pipe/ap_pipe.py
This commit adds support for coadd templates to `ap_pipe`. Per a comment by @mrawls (old line 192), `ap_pipe` retains the ability to use visit templates. The default behavior is unchanged when running `ap_pipe` from the command line, but uses a coadd when running from `ap_verify`.
> DM-11422: Adapt prototype pipeline to use coadds as templates

- python/lsst/ap/pipe/ap_pipe.py
`ap_pipe` has been changed to always report "full" metadata (i.e., metadata for a task and all its subtasks) for each pipeline stage. This is the format expected by `ap_verify`, which needs to compute metrics for both top-level- and subtasks.
For `ImageDifferenceTask`, which is currently the only top-level task called using `parseAndRun()`, I've opted to recover the metadata using the Butler rather than implementing [DM-11935](https://jira.lsstcorp.org/browse/DM-11935). However, this seems a rather clumsy solution -- in order to get the metadata for a (sub)task, I need to both explicitly identify the associated top-level task and pass in a parsed data ID. This approach seems like it will be difficult to scale up to a more generic measurement-handling system. Is there a way to cast a …
> DM-12432: Fix timing measurement construction

- python/lsst/ap/pipe/ap_pipe.py
This patch allows the user to disable `ap_pipe`'s short-circuiting, which causes problems with multi-visit or multi-CCD runs. It also fixes a Python 3 bug introduced in #7.
> DM-12535: Wrap ap_verify and run it over HITS dataset

- python/lsst/ap/pipe/ap_pipe.py
This PR adds a comment explaining why some DECam file types are explicitly ignored on ingestion, to avoid developer confusion when reviewing the code.
> DM-12851: Determine whether dataset framework can be made generic

- python/lsst/ap/pipe/ap_pipe.py
The previous code required that ap_pipe's output repo be a relative path to an immediate subdirectory of the user's working directory, which caused crashes when an unaware user provided a different path.
> DM-12938: ap_pipe crashes if --output is absolute path

- python/lsst/ap/pipe/ap_pipe.py
The new code allows `ap_pipe` to accept 1-2 standard Butler repositories as input (so long as they are DECam data). Runs on repositories created by `ap_verify` can still be made by passing input = "\<repo>/ingested" and --calib = "\<repo>/calibingested".
> DM-13535: Accept idiomatic input repositories

- COPYRIGHT
- LICENSE
- python/lsst/ap/pipe/ap_pipe.py
- python/lsst/ap/pipe/selectImages.py
- tests/test_appipe.py
This PR removes the adapters between the `ap_pipe` code and `ap_verify`. The adapters were based on the assumption that `ap_verify` should see the entire workspace as one large repository. Since instead it should have separate input, calib, and output repositories (of its choosing, not `ap_pipe`'s), the adapters are counterproductive (in hindsight, they should not have pushed the wrapped functions out of the API).
API changes must be synced with lsst-dm/ap_verify#21.
> DM-13536: Use repositories more idiomatically

- .travis.yml
- bin.src/ap_pipe.py
- config/calexpTemplates.py
- config/makeCoaddTempExp_goodSeeing.py
- python/lsst/ap/pipe/apPipeParser.py
- python/lsst/ap/pipe/apPipeTaskRunner.py
- python/lsst/ap/pipe/ap_pipe.py
- python/lsst/ap/pipe/selectImages.py
- setup.cfg
- tests/test_appipe.py
This is a complete refactoring of `ap_pipe`, preserving existing functionality as much as possible (some changes to the command-line interface were unavoidable). No attempt was made to make use of features enabled by `CmdLineTask`, such as parallelism support or `obs_` package handling; such changes are out of scope for the ticket.
`ApPipeTask` requires both a custom runner and a custom parser to support the source association database and input template repositories. Unfortunately, due to limited support for subclassing, this meant duplicating a large amount of code from `pipe.base.TaskRunner` and `pipe.base.ArgumentParser`. I hope we can remove the duplicate code quickly as the indicated tickets get resolved.
> DM-13163: Refactor ap_pipe to use CmdLineTask primitives

- python/lsst/__init__.py
- python/lsst/ap/__init__.py
- python/lsst/ap/pipe/__init__.py
- python/lsst/ap/pipe/apPipeParser.py
- python/lsst/ap/pipe/apPipeTaskRunner.py
- python/lsst/ap/pipe/ap_pipe.py
- python/lsst/ap/pipe/selectImages.py
- setup.cfg
- tests/test_appipe.py
This PR fixes several bugs in how datarefs were passed to `ApPipeTask`. It also updates `ap_pipe` to current style standards and removes use of `future`.
> DM-14359: Fix data ID handling in ap_*

- python/lsst/ap/pipe/__init__.py
- python/lsst/ap/pipe/selectImages.py
This PR fixes an `ImportError` in `selectImages.py` that propagates to imports of `lsst.ap.pipe`. The `__init__` file for `ap.pipe` may also be edited as part of this PR, but I'm waiting for confirmation from @ebellm that it's safe to do so.
> DM-14494: selectImages.py depends on defunct lsst.geom

- python/lsst/ap/pipe/ap_pipe.py
This PR updates `ApPipeConfig` to account for API changes in `AssociationTask`. It also ~adds a temporary workaround for DM-14507 (though I'm not sure why it works, since `AssociationTask` does the same thing internally) and~ improves the input validation of `ApPipeConfig`.
> DM-14497: ap_pipe doesn't know filters for AssociationTask

- python/lsst/ap/pipe/apPipeTaskRunner.py
- python/lsst/ap/pipe/ap_pipe.py
Rename methods according to RFC-352.
ParseAndRun now calls runDataRef
> DM-2639: {{Standardize primary method names, run/runDataRef, across PipeTasks}}

- doc/lsst.ap.pipe/pipeline-tutorial.rst
- python/lsst/ap/pipe/apPipeTaskRunner.py
- python/lsst/ap/pipe/ap_pipe.py
This PR removes the database-in-repository model from `ap_pipe` as well as all the code that was necessary to enforce it. SQLite configs are no longer allowed to specify `:memory:`, as testing revealed that in-memory databases are incompatible with the requirement that the database be fully initialized before `AssociationTask` is created. The documentation has been updated to emphasize that the user must always choose a database location in addition to the usual output repository.
> DM-15096: Cannot reuse association database with ApPipeTask reruns

- .gitignore
- Sconstruct
- doc/ap_pipe/index.rst
- doc/lsst.ap.pipe/getting-started.rst
- doc/lsst.ap.pipe/pipeline-overview.rst
- doc/lsst.ap.pipe/pipeline-tutorial.rst
- python/lsst/ap/pipe/ap_pipe.py
This PR moves most of the config defaults out of the source code (see lsst/ap_verify_hits2015#9, lsst/obs_decam#88, and lsst/obs_subaru#143). Note that, depending on the templates or refcats being used, runs of `ap_pipe` are much more likely to need a user config file.
This PR also makes some minor maintenance updates to `ap_pipe`.
> DM-12315: Generalize ap_pipe to non-HiTS data

- python/lsst/ap/pipe/apPipeParser.py
This PR fixes a misprint in `ap_pipe.py`'s help text, discovered while debugging lsst/ap_verify#57.
> DM-13887: Let ap_verify process multiple images per instance

- python/lsst/ap/pipe/ap_pipe.py
This PR lets association be skipped using the standard `--reuse-output-from` command-line argument; previously association would be rerun even if the user requested that it be skipped. Testing whether association has already been performed requires the `isVisitProcessed` function introduced in lsst/dax_ppdb#9.
> DM-14019: Allow ap_pipe to skip association

- python/lsst/ap/pipe/ap_pipe.py
- setup.cfg
- tests/SConscript
This PR prints a warning (once per process) if the user includes association in the set of skippable tasks. It also does some unrelated package cleanup.
> DM-17521: Add warning when ap_pipe skips association

- .gitignore
- COPYRIGHT
- bin.src/ap_pipe.py
- bin.src/make_ppdb.py
- doc/lsst.ap.pipe/pipeline-tutorial.rst
- python/lsst/ap/pipe/ap_pipe.py
- python/lsst/ap/pipe/make_ppdb.py
- tests/test_makeppdb.py
This PR creates a `make_ppdb.py` script that takes the same config arguments as `ap_pipe.py` and only calls `Ppdb.makeSchema`, then removes the corresponding call from `ApPipeTask`*. This gives users more control over database creation and avoids certain race conditions when `ApPipeTask` is run in parallel.
*For backward-compatibility, the call from `ApPipeTask` may be reinstated and scheduled for removal on another ticket. See discussion on [`#dm-alert-prod`](https://lsstc.slack.com/messages/C2B6X08LS/).
> DM-16606: ap_pipe should not create DB automatically

- tests/test_appipe.py
- ups/ap_pipe.table
Pair coded with @kfindeisen. The new tests require the ap_pipe_testdata package.
> DM-13567: Add tests to ap_pipe

- python/lsst/ap/pipe/ap_pipe.py
- tests/test_appipe.py
Comment out diaForcedSourceTask for now.
> DM-18736: Convert ap_association to use Pandas data frames (rather than afw::table) as an interface

- doc/lsst.ap.pipe/index.rst
- doc/lsst.ap.pipe/pipeline-tutorial.rst
- doc/lsst.ap.pipe/ppdb.rst
- doc/lsst.ap.pipe/scripts/make_ppdb.py.rst
- python/lsst/ap/pipe/make_ppdb.py
This PR adds a script topic page on `make_ppdb.py`, as well as a short guide to using it. The guide hopefully makes it clear that `make_ppdb.py` should be configured the same as `ap_pipe.py`.
> DM-20384: Clarify usage of make_ppdb.py script

- python/lsst/ap/pipe/ap_pipe.py
- tests/test_appipe.py
This PR writes an `apdb_marker` dataset (introduced in lsst/obs_base#182) to the repository once association and forced photometry finish (successfully or not). It also uses the new dataset to streamline completion checking, and makes some improvements to the relevant unit tests.
This code will need to be updated once [DM-22039](https://jira.lsstcorp.org/browse/DM-22039) merges.
> DM-21877: Create "marker" Butler dataset for PPDB

- python/lsst/ap/pipe/ap_pipe.py
- tests/test_appipe.py
Modify runAssociation for new method inputs.
Fix bug in runAssociation
Add validation test for HTM level.
Debug validation.
> DM-22478: Lightly restructure ap_association tasks and create new DiaObject/DiaSource pre-loading task.

- python/lsst/ap/pipe/make_apdb.py
This PR adds a workaround for [DM-24435](https://jira.lsstcorp.org/browse/DM-24435), which otherwise causes `ap_verify` to crash when run with standard HSC configs.
This PR may not need to be merged; see lsst/pex_config#55.
> DM-24259: Create “stub“ Gen2 HSC dataset for CI testing

- doc/lsst.ap.pipe/apdb.rst
- doc/lsst.ap.pipe/getting-started-gen2.rst
- doc/lsst.ap.pipe/getting-started.rst
- doc/lsst.ap.pipe/index.rst
- doc/lsst.ap.pipe/pipeline-overview.rst
- doc/lsst.ap.pipe/pipeline-tutorial-gen2.rst
- doc/lsst.ap.pipe/pipeline-tutorial.rst
- pipelines/ApPipe.yaml
- python/lsst/ap/pipe/ap_pipe.py
This PR makes some code changes to conform to lsst/ap_association#86, and adds a pipeline config file to the repository (we may later want to move it to `pipe_tasks`, but I think doing so at this point would be confusing). For readability, I've put the documentation in different commits from the changes they document.
I've moved the old documentation to "Gen 2" files and created a modified "Gen 3" copy under the original filenames. GitHub displays this as an in-place change; I'm not sure whether it will be easier to review the changes that way, or as a completely new document.
> DM-21939: Create Gen 3 AP Pipeline

- python/lsst/ap/pipe/ap_pipe.py
Add config and usage of doWriteWarpedExp.
Remove config validation.
Fix name.
> DM-24327: Include coadd cutouts in alert packets

- pipelines/ApPipe.yaml
- python/lsst/ap/pipe/ap_pipe.py
This PR modifies a call to `DiaPipelineTask` (in response to lsst/ap_association#97). It also changes the AP pipeline's Gen 3 name for image differencing to match its default name, which makes it much easier to configure generic metric pipelines that depend on `ImageDifferenceTask`.
> DM-21919: Run ap_verify end-to-end in Gen 3

- doc/lsst.ap.pipe/apdb.rst
- doc/lsst.ap.pipe/pipeline-tutorial-gen2.rst
- doc/lsst.ap.pipe/pipeline-tutorial.rst
- python/lsst/ap/pipe/make_apdb.py
- tests/test_makeapdb.py
This PR removes the `make_apdb.py` script's dependence on `pipe_base` and on `ApPipeConfig`, making it forward-compatible with Gen 3. As a side effect, the script now loads configs at a lower level, requiring changes to calling scripts.
> DM-22663: Reimplement make_apdb.py for Gen 3

- tests/test_appipe.py
- ups/ap_pipe.table
This PR compensates for the removal of the `obs_decam` dependency from lsst/ap_pipe_testdata#3 by adding a new dependency, and ensuring unit tests check separately for the testdata and the obs package being available.
> DM-26326: Remove obs dependency from ap_verify_testdata and ap_pipe_testdata

- pipelines/APTemplate.yaml
This ticket adds a starter gen3 pipeline for building coadds (for use as diffim templates) from scratch.
> DM-28107: Convert/ingest PS1 and Gaia refcats into gen3 repo for DECam use

- python/lsst/ap/pipe/ap_pipe.py
This PR makes the implementation of `--reuse-outputs-from` slightly more generic.
> DM-29121: ApPipeTask's --reuse-outputs-from does not work with external preprocessing

- bps/ApPipeTemplate_bps.yaml
- pipelines/ApPipe.yaml
- pipelines/DarkEnergyCamera/ApPipe.yaml
- pipelines/DarkEnergyCamera/ApPipe_hits2015-3.yaml
- pipelines/DarkEnergyCamera/RunIsrForCrosstalkSources.yaml
- pipelines/DarkEnergyCamera/RunIsrWithCrosstalk.yaml
- pipelines/DarkEnergyCamera/RunIsrWithoutInterChipCrosstalk.yaml
- pipelines/HyperSuprimeCam/ApPipe.yaml
- pipelines/ProcessCcd.yaml
This PR adds a top-level `ApPipe.yaml` to `ap_pipe`. It imports from a new standalone `ProcessCcd.yaml` in the same location. In addition, there are two new subdirectories for DECam and HSC. These contain camera-specific pipelines and configurations which import from the main `ApPipe.yaml`.
> DM-29221: Add ApPipe.yaml pipelines to appropriate repos

- pipelines/ApPipe.yaml
- python/lsst/ap/pipe/ap_pipe.py
- tests/test_appipe.py
Debug ApPipe use of transformDiaSourceCat.
> DM-29147: Switch from using mapApData to new pipeline task and functors.

- pipelines/ApPipe.yaml
This PR does not explicitly set `doScaleDiffimVariance` in the AP pipeline. We will turn it on at the task level instead.
> DM-29344: Investigate the CI differences between Gen 2 and 3 in COSMOS field

- pipelines/ApPipe.yaml
- python/lsst/ap/pipe/ap_pipe.py
This PR documents the configs in `ApPipe.yaml` and extends them to cover all coadd-related connections in the main pipeline chain. This prevents downstream pipeline edits that only touch templates from creating inconsistent configs.
> DM-30563: ap_verify failing to find dataset type fakes_deepDiff_warpedExp

- tests/test_createApFakes.py
- tests/test_matchApFakes.py
This PR fixes some unit tests broken by lsst/pipe_base#182.
> DM-28668: PipelineTask unit test framework bypasses dimensions checks

- tests/test_makeapdb.py
The ap_association path could either be a reference to an
AP_ASSOCIATION_DIR environment variable or a fully expanded path
to the ap_association package.
Needed to support lsst/ap_association#119
> DM-30985: Change test to use case-insensitive search for "ap_association"

- python/lsst/ap/pipe/ap_pipe.py
- tests/test_appipe.py
This PR adds a missing argument to the `DiaPipelineTask` call, and updates the unit tests to catch such problems in the future.
> DM-31220: Use new DiaPipelineTask API in ApPipeTask

- python/lsst/ap/pipe/metrics.py
This PR fixes some deprecation warnings related to the task logger transition. It does not attempt to remove local construction of `lsst.log.Log` objects.
> DM-31419: Update logger usage

- doc/lsst.ap.pipe/apdb.rst
- doc/lsst.ap.pipe/pipeline-tutorial-gen2.rst
- doc/lsst.ap.pipe/pipeline-tutorial.rst
- pipelines/ApPipe.yaml
- pipelines/DarkEnergyCamera/ApPipe.yaml
- pipelines/HyperSuprimeCam/ApPipe.yaml
- python/lsst/ap/pipe/make_apdb.py
- tests/test_appipe.py
Lots of small changes:
- API changed, check dax_apdb for details
- afw support dropped, we do everything with Pandas and yaml config
- no need to override default `isolation_level` in config
ap_verify works OK after all changes.
> DM-31458: Update ap_pipe for changes in APDB API

- pipelines/HyperSuprimeCam/ApTemplate.yaml
This PR adds the skyCorrectionTask step to ApTemplate.yaml for HSC. I also fixed a typo.
> DM-33692: HSC's ApTemplate pipeline is missing skyCorr step

- tests/test_makeapdb.py
Dropped one unit test, `extra_schema_file` is deprecated, no need to test its value.
> DM-34480: Update unit test for changes in APDB configuration

- pipelines/ApPipe.yaml
- pipelines/ApPipeWithFakes.yaml
- pipelines/ApTemplate.yaml
- pipelines/HyperSuprimeCam/ApTemplate.yaml
- pipelines/LsstCamImSim/ApTemplate.yaml
This PR significantly reworks the AP pipelines, making two major changes:
- the [DM-30210](https://jira.lsstcorp.org/browse/DM-30210) workarounds are now done at the contract level, not the parameter/config level. This arrangement is harder to read, but is much more portable to importing pipelines.
- the `ApPipeWithFakes` pipeline no longer imports `ApPipe`, giving it independent task labels and contracts. This change is strictly for the benefit of `ap_verify` (which needs to be careful about distinguishing fakes and non-fakes tasks), and does not improve `ap_pipe` itself.
> DM-32694: Split AP pipeline into ApPipeWithFakes

- python/lsst/ap/pipe/ap_pipe.py
This PR removes references to `getFilterLabel` and similarly-named methods, replacing them with `getFilter` (etc.) methods backed by `FilterLabel`.
> DM-27177: Deprecate transitional getFilterLabel API

- pipelines/DarkEnergyCamera/ProcessCcd.yaml
- pipelines/HyperSuprimeCam/ProcessCcd.yaml
- pipelines/LsstCamImSim/ProcessCcd.yaml
- pipelines/ProcessCcd.yaml
These were explicitly set to 25 when drp_pipe wanted kernelSize to be 21
during their validation. Now that the default is switched to 25, these
overrides are no longer required.
> DM-34698: Remove config overrides setting kernelSize to 25

- config/HSC/makeWarp.py
- config/LSSTCam-imSim/makeWarp.py
- pipelines/ApPipe.yaml
- pipelines/ApPipeWithFakes.yaml
- pipelines/ApTemplate.yaml
- pipelines/ProcessCcd.yaml
This PR adds a config to the imSim and HSC camera-specific makeWarp config files.
> DM-35359: Set doApplyFinalizedPsf to False for all AP makeWarp steps, for reals

- config/DECam/processCcdWithFakes.py
- config/HSC/calibrate.py
- config/HSC/processCcdWithFakes.py
This PR fixes some HSC configs that caused an error when running ApPipeWithFakes. The task injects fakes to visits is sneaky because it calls calibrateTask a second time with most things (like astrometry and photometry) turned off. The PR also adds a config file for DECam so its visit-level fakes injection properly picks up camera-specific calibrateTask configs too.
> DM-34711: Reprocess HSC Cosmos dataset with Fakes

- pipelines/ApTemplate.yaml
Running updateVisitSummary here (as is done in DRP) would be wasteful, as there are no updated calibration objects being produced in this pipeline.
> DM-35207: Reset MakeWarp visitSummary connection in ApTemplate.yaml

- pipelines/HyperSuprimeCam/ApPipeWithFakes.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
- python/lsst/ap/pipe/createApFakes.py
This modifies the fake injection to increase the magnitude range and density of fakes. 
Setting new defaults for using fake-based metrics that require higher statistics. 
Probably density ends up being higher than needed. This would be a point of discussion before merging.
> DM-39467 Increase fake source density

- doc/lsst.ap.pipe/apdb.rst
- doc/lsst.ap.pipe/getting-started.rst
- doc/lsst.ap.pipe/pipeline-tutorial.rst
This PR fixes a large number of build problems and outdated information in the `ap_pipe` documentation, then updates the tutorial to use `ap_verify_ci_hits2015` instead of the obsolete `ap_verify_hits2015`.
> DM-36477: Remove ap_verify_hits2015 dataset

- pipelines/DarkEnergyCamera/ApPipeWithFakes.yaml
- pipelines/DarkEnergyCamera/ProcessCcd.yaml
- pipelines/DarkEnergyCamera/RunIsrForCrosstalkSources.yaml
- pipelines/DarkEnergyCamera/RunIsrWithCrosstalk.yaml
- pipelines/DarkEnergyCamera/RunIsrWithoutInterChipCrosstalk.yaml
- pipelines/HyperSuprimeCam/ApPipeWithFakes.yaml
- pipelines/HyperSuprimeCam/ApTemplate.yaml
- pipelines/HyperSuprimeCam/ProcessCcd.yaml
- pipelines/LsstCamImSim/ApPipe.yaml
- pipelines/LsstCamImSim/ApTemplate.yaml
- pipelines/LsstCamImSim/ProcessCcd.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
This PR removes a large amount of duplicate pipeline configuration, particularly base (`_ingredients`) configs and tasks copied to instrument-specific pipelines. This leaves the pipelines cleaner and with clearer responsibilities, and will prevent changes to the base pipeline from unexpectedly not working.
Unfortunately, not all of the duplicate configs in the instrument pipelines could be removed, as some are still needed as workarounds for DRP-specific settings/plugins lurking in the `obs` package configs.
> DM-40210: Clean up ap_pipe and ap_verify pipelines

- pipelines/LsstCamImSim/ApPipeWithFakes.yaml
Adding the yaml file for ImSim ApPipeWithFakes which was missing.
Requesting help to test with DC2 data at usdf.
> DM-39662 Add ApPipeWithFakes.yaml to LsstCamImSim

- config/DECam/characterizeImage.py
- config/HSC/characterizeImage.py
The config fields were removed because they had deprecations in place for over a year, and were deprecated because they never did anything in the first place.
> DM-34769: Remove characterizeImage refObjLoader

- pipelines/LSSTCam-imSim/ApPipeWithFakes.yaml
Corrected missed file in original fix. Changed `LSSTCamImSim` to `LSSTCam-imSim` in response to RFC-775.
> DM-33453: Update pipeline reference in response to RFC-775. (Hotfix)

- pipelines/DECam/ApPipe.yaml
- pipelines/DECam/ApPipeCalibrateImage.yaml
- pipelines/DECam/ApPipeWithFakes.yaml
- pipelines/HSC/ApPipe.yaml
- pipelines/HSC/ApPipeWithFakes.yaml
- pipelines/LSSTCam-imSim/ApPipe.yaml
- pipelines/LSSTCam-imSim/ApPipeWithFakes.yaml
- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeCalibrateImage.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
This PR adds support for `rbClassify` to `ApPipe` and its variant pipelines, now that we have a suitable model in the major repos of interest (`/repo/main` and the `ap_verify` datasets). ~It also adds the `msg` argument to all input/output contracts, to make them a bit more user-friendly.~
> DM-42217: Incorporate ModelPackage Butler datasets into ap_verify

- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeCalibrateImage.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
- pipelines/_ingredients/ApTemplate.yaml
This PR fixes missing `filterDiaSrcCat` in the secondary pipelines (a pipeline-breaking bug since the default connections for `rbClassify` and `transformDiaSrcCat` assume it), and then adds a `msg` argument to each connection contract.
> DM-42762: Make ApPipe contracts more human-friendly

- pipelines/LATISS/ApPipe.yaml
This PR removes the pre-emptive blocker that prevented `rbClassify` from being run in LATISS (specifically, Prompt Processing). It must be merged after lsst-dm/prompt_processing#125.
> DM-42220: Incorporate ModelPackage Butler datasets into Prompt Processing

- pipelines/_ingredients/ApPipeWithFakes.yaml
This PR removes the disruptive "WithFakes" suffixes from tasks in `ApPipeWithFakes`. It must be merged together with lsst/ap_verify#213.
> DM-42419: Break up ApVerify into pure with- and without-fakes pipelines

- python/lsst/ap/pipe/make_apdb.py
The `makeSchema` method is now a class method instead of instance method and it takes configuration object as a parameter.
> DM-42489: Update factory method for changes in Apdb.makeSchema interface

- bps/clustering/clustering_ApPipe.yaml
- bps/clustering/clustering_ApPipeWithFakes.yaml
This PR updates the BPS clustering files to use the same task labels as their corresponding pipeline (with one exception; `clustering_ApPipeWithFakes.yaml` does not include `createFakes`). These changes are updates in response to #156, #157, and #163.
> DM-43037: ap_pipe BPS scripts use old task names

- python/lsst/ap/pipe/metrics.py
- tests/test_metrics.py
This PR implements `PipelineTimingMetricTask`, which allows timing of pipelines that are linear or close to linear. It's designed to work on `ApPipe` or closely related pipelines (e.g., `ApVerify`), but is not a general-purpose tool.
> DM-40400: Create total AP pipeline timing metric

- doc/lsst.ap.pipe/apdb.rst
- doc/lsst.ap.pipe/pipeline-tutorial.rst
- pipelines/DECam/ApPipe.yaml
- pipelines/DECam/ApPipeCalibrate.yaml
- pipelines/DECam/ApPipeWithFakes.yaml
- pipelines/HSC/ApPipe.yaml
- pipelines/HSC/ApPipeCalibrate.yaml
- pipelines/HSC/ApPipeWithFakes.yaml
- pipelines/LSSTCam-imSim/ApPipe.yaml
- pipelines/LSSTCam-imSim/ApPipeCalibrate.yaml
- pipelines/LSSTCam-imSim/ApPipeWithFakes.yaml
- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeCalibrate.yaml
- python/lsst/ap/pipe/make_apdb.py
`make_apdb` will be replaced by `apdb-cli` sub-command, for now we keep it for compatibility reasons, but update it for new APDB API. This script depends on using pex_config for Apdb configuration, that will be replaced eventually with something different, we may want to drop this script before that change.
> DM-43414: Update make_apdb module for changes in APDB API

- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
Note that most analysis_tools Tasks require the input connections to be named 'data'
> DM-43711: Add contracts for analysis_tools plots

- bps/clustering/clustering_ApPipe.yaml
- bps/clustering/clustering_ApPipeWithFakes.yaml
Modified bps clustering yamls to group the right tasks.
> DM-40388-batchfix: Fix bps clustering configs to match calibrateImage adoption

- doc/lsst.ap.pipe/apdb.rst
- doc/lsst.ap.pipe/getting-started.rst
- doc/lsst.ap.pipe/index.rst
- doc/lsst.ap.pipe/pipeline-tutorial.rst
- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeCalibrate.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
- tests/test_pipelines.py
This PR modifies the AP pipelines to use new-style configs instead of the `diaPipe.apdb` field. It must be merged after lsst/ap_association#210. This is a major API change to the pipeline, and the documentation has been updated accordingly.
> DM-43416: Migrate AP code to external APDB configs

- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeCalibrate.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
This PR adds the `GetRegionTimeFromVisitTask` from lsst/pipe_tasks#920 to the AP pipelines.
The use of a contract for its input connections is a bit questionable, since the task does not actually use the input catalog for anything and so it's somewhat interchangeable. For now, the contract enforces that the task be run as late as possible, to minimize inconsistencies from parallel reads and writes to the APDB.
Important: this PR should not be merged until `/repo/main` has been migrated to dimensions-config `daf_butler` 6 or later; otherwise, it will break AP precursor processing.
> DM-43020: Implement region and time extraction for preload

- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
Trailed sources are no longer filtered in diaPipe, but filterDiaSourceCatalog.
> DM-41063: Update longTrailedSources connection

- pipelines/DECam/ApPipe.yaml
- pipelines/DECam/ApPipeCalibrate.yaml
- pipelines/DECam/ApPipeWithFakes.yaml
- pipelines/DECam/ApTemplate.yaml
- pipelines/HSC/ApPipe.yaml
- pipelines/HSC/ApPipeCalibrate.yaml
- pipelines/HSC/ApPipeWithFakes.yaml
- pipelines/HSC/ApTemplate.yaml
- pipelines/LSSTCam-imSim/ApPipe.yaml
- pipelines/LSSTCam-imSim/ApPipeCalibrate.yaml
- pipelines/LSSTCam-imSim/ApPipeWithFakes.yaml
- pipelines/LSSTCam-imSim/ApTemplate.yaml
- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeCalibrate.yaml
- tests/test_pipelines.py
- ups/ap_pipe.table
This PR fixes a number of self-consistency problems with the AP pipelines, related to the migration from `characterizeImage`/`calibrate` to `calibrateImage` (#166). It also removes references to the old APDB configuration system (something I should have done on #182).
> DM-44411: Fix bit-rot in AP pipelines

- python/lsst/ap/pipe/createApFakes.py
- tests/test_createApFakes.py
- tests/test_metrics.py
Note that (a) for rings and discrete skymap these return almost the same polygon (which was incorrect necessitating the deprecation); (b) using the outer polygon may have been the original intention in this task; (c) this task is soon to be deprecated and removed on DM-40855.
> DM-44796: Replace deprecated getInnerSkyPolygon() with getOuterSkyPolygon()

- pipelines/DECam/ApPipe.yaml
- pipelines/DECam/ApPipeWithFakes.yaml
- pipelines/LSSTComCamSim/ApPipe.yaml
- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
This PR divides the AP pipelines into `preload`, `prompt`, and `afterburner` subsets, and ensures the pipeline variants are mutually consistent.
> DM-43418: Divide AP pipeline into preload and prompt subsets

- pipelines/DECam/ApPipe.yaml
- pipelines/DECam/ApPipeWithFakes.yaml
- pipelines/LSSTComCamSim/ApPipe.yaml
- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
Adding mpSkyEphemerisQuery, which replaces SkyBot in querying mpSky for ssObjects in the pre-load step.
> DM-42576: Write task to compute predicted positions for an upcoming visit

- pipelines/_ingredients/ApPipe.yaml
Significantly faster than recalculating the PSF at the location of every source, but not as accurate
> DM-46050: Use average PSF for packaged alerts

- config/HSC/makeWarp.py
- config/LSSTCam-imSim/makeWarp.py
The configs for makeWarp were accidentally broken when the coaddBase config was (correctly) removed in favor of new configs for makeDirectWarp and makePsfMatchedWarp.  Now that we're letting makeWarp live a bit longer while we test its replacements off the main branch, we probably want its config overrides working again.
> DM-46708: restore makeWarp configurations to working order

- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
This PR turns on alert generation (but not writing or distribution) in the base `ApPipe` pipeline. This ensures that this code is exercised and is counted in the run time (which can be significant, for crowded or noisy fields).
> DM-47067: Enable alert generation in ap_pipe

- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
Change contracts in ApPipe and ApPipeWithFakes to match the changes in pipe_task/getRegionTimeFromVisit's input.
> tickets/DM-47318 - change getRegionTimeFromVisit inputs

- pipelines/LSSTComCam/SingleFrame.yaml
- pipelines/_ingredients/SingleFrame.yaml
My understanding of why I was instructed to make these changes in the particular structure I did: 
As-is, SingleFrame.yaml exists in `prompt_processing` but nowhere else. We want a system in which `ap_pipe` (and `ci_pipe` and `drp_pipe`) sit on top of everything else and describe pipeline functionality via yamls. All `prompt_processing` pipeline yamls should reference and modify counterparts in `ap_pipe`. At the moment, SingleFrame.yaml is a standalone `prompt_processing` pipeline, so in addition to adding single-frame association to it, I was asked to also move it into `ap_pipe` in a traditional LSSTComCam -> _ingredients reference chain.
> DM-47620 Adding single-frame fallback pipelines

- pipelines/DECam/RunIsrForCrosstalkSources.yaml
- pipelines/DECam/RunIsrWithCrosstalk.yaml
- pipelines/DECam/RunIsrWithoutInterChipCrosstalk.yaml
- pipelines/DECam/SingleFrame.yaml
- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
- pipelines/_ingredients/ApPipeWithIsrTaskLSST.yaml
- pipelines/_ingredients/SingleFrame.yaml
- tests/test_pipelines.py
This PR fixes outstanding issues with subset definitions, and adds unit tests to check the more mechanical ones.
> DM-48044: Test subset definitions in ap_pipe pipeline tests

- bps/clustering/clustering_ApPipe.yaml
- bps/clustering/clustering_ApPipeWithFakes.yaml
- doc/lsst.ap.pipe/getting-started.rst
- doc/lsst.ap.pipe/pipeline-bps.rst
- pipelines/DECam/ApPipe.yaml
- pipelines/DECam/ApPipeWithFakes.yaml
- pipelines/HSC/ApPipe.yaml
- pipelines/HSC/ApPipeWithFakes.yaml
- pipelines/LATISS/ApPipe.yaml
- pipelines/LSSTCam-imSim/ApPipe.yaml
- pipelines/LSSTCam-imSim/ApPipeWithFakes.yaml
- pipelines/LSSTCam/ApPipe.yaml
- pipelines/LSSTCam/ApPipeWithFakes.yaml
- pipelines/LSSTComCam/ApPipe.yaml
- pipelines/_ingredients/ApPipe.yaml
- pipelines/_ingredients/ApPipeWithFakes.yaml
- pipelines/_ingredients/ApPipeWithIsrTaskLSST.yaml
- pipelines/_ingredients/SingleFrame.yaml
- pipelines/_ingredients/SingleFrameWithIsrTaskLSST.yaml
- tests/test_pipelines.py
This is a major reorganization, so I tried to break it apart into multiple steps with self-contained commits. These can be rebased after review for a cleaner commit history, but I think they will make the changes easier to follow.
There are also separate commits for most of the ApPipe and ApPipeWithFakes pipelines, which appear more complicated now since we can't rely on the task defaults. This can be simplified in future work when we update the task defaults, or by moving the connections definitions into shared config files, such as in the current `config/DECam/runIsrWithCrosstalk.py`.
> DM-49875: rename task labels and dataset names for RFC-1088
